
name: dreamviews

dependencies:
  - ipython                         # development
  - requests==2.31.0                # web scraping
  - beautifulsoup4== 4.12.3         # web scraping
  - conda-forge::tqdm==4.66.0       # web scraping (progress bars)
  - chardet==5.2.0                  # cleaning (web scraping?)
  - langdetect==1.0.9
  - pycountry==23.12.11