name: dreamviews
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython             # development
  - tqdm                # progress bars
  - numpy               # data analysis
  - pandas              # data analysis
  - scipy               # data analysis
  - pingouin            # data analysis - statistics
  - scikit-learn        # data analysis - machine learning
  - matplotlib          # data visualization
  - seaborn             # data visualization
  - colorcet            # data visualization - colormaps
  - geopandas           # data visualization - choropleth
  - beautifulsoup4      # web scraping
  - unidecode           # text cleaning - ascii conversion
  - pyahocorasick       # text cleaning - contraction conversion
  - nltk                # natural language processing
  - gensim              # natural language processing
  - spacy               # natural language processing
  - python-levenshtein  # natural language processing - silence gensim warning
  - pooch               # data management - fetching remote files
  - make                # manuscript compilation
  - pip
  - pip:
    - pycountry         # demographics - ISO country codes
    - matplotlib-venn   # data visualization - venn diagram
    - contractions      # text cleaning - expand contractions
    - langdetect        # text cleaning - detect language
    # - shifterator       # text analysis - word shifts
    - git+https://github.com/ryanjgallagher/shifterator.git  # For >=3.11 Python compatibility
    - liwc              # text analysis - LIWC
